### ISSUE TITLE
carthage update failed

### ISSUE THREAD

**Issue by miliPolo** [mapbox/mapbox-scenekit#37]
Hello,i can't build this project, i found the code has some error
log info:
*** Downloading binary-only framework Mapbox-iOS-SDK at "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json"
*** Skipped downloading mapbox-scenekit.framework binary due to the error:
	"Bad credentials"
*** Skipped downloading mapbox-events-ios.framework binary due to the error:
	"Bad credentials"
*** Building scheme "MapboxMobileMetrics" in MapboxMobileEvents.xcodeproj
*** Building scheme "MapboxSceneKit" in MapboxSceneKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project scenekit-volumetric-weather-master/Carthage/Checkouts/mapbox-scenekit/MapboxSceneKit.xcodeproj -scheme MapboxSceneKit -configuration Release -derivedDataPath

**Comment by avi-c** [comment]
Hi @miliPolo . I hadn't encountered that error before, but googling for the error message I found this:
https://stackoverflow.com/questions/39578496/carthage-error-bad-credentials

Looks like you need to set up or fix your keychain credentials for github in order to successfully download the dependencies. I hope the link contains the info you need to address the issue.
